# Generated by Django 5.2.7 on 2025-11-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('clase_nombre', models.CharField(max_length=100)),
                ('clase_tema', models.CharField(max_length=100)),
                ('clase_horario', models.CharField(max_length=50)),
                ('clase_cupo', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_nombre', models.CharField(max_length=100)),
                ('inst_apellido', models.CharField(max_length=100)),
                ('inst_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('inst_especialidad', models.CharField(max_length=100)),
                ('inst_turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('socio_id', models.AutoField(primary_key=True, serialize=False)),
                ('socio_nombre', models.CharField(max_length=100)),
                ('socio_apellido', models.CharField(max_length=100)),
                ('socio_docnro', models.CharField(max_length=20, unique=True)),
                ('socio_fecnacimiento', models.DateField(blank=True, null=True)),
                ('socio_fecalta', models.DateField(blank=True, null=True)),
                ('socio_fecbaja', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
