# Generated by Django 5.2.7 on 2025-11-03 00:56

import equipamiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=equipamiento.models.generar_code, max_length=32, unique=True)),
                ('nombre_ref', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('accesorio', 'Accesorio'), ('estiramiento', 'Estiramiento'), ('funcional', 'Funcional')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nro_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('baja', 'De baja')], default='activo', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
